#pragma once
#include <stdlib.h>
#include <cstring>
#include <stdio.h>

struct SCODIntConst
{
	char* name;
	int value;

	SCODIntConst(const char* _name, int _value)
	{
		int size = (int) strlen(_name);
		char* tmp = (char*) malloc((size + 1) * sizeof(char));
		if (!tmp)
		{
			printf("Error: SCODIntConst(): Memory allocation failed.\n");
			return;
		}
		memcpy(tmp, _name, size);
		tmp[size] = '\0';
		name = tmp;
	}

	~SCODIntConst()
	{
		free(name);
	}
};

// Define the hardcoded internal constants here:
// GoG Version EN
//ToDo:Check for different .exe Versions

SCODIntConst InternalConsts[] =
{
	{"UNUSED", 0},
	{"TIMENEVER", 0},
	{"NOWARE", 24}, // 18h
	{"MAXPRODCNT", 15}, // 0Fh
	{"MAXHAUS", 500},
	{"BODEN", 11},
	{"ROHSTOFF", 9},
	{"ROHSTWACHS", 10},
	{"ROHSTERZ", 12},
	{"WOHNUNG", 13},
	{"WALD", 26},
	{"WEIDETIER", 4},
	{"HANDWERK", 1},
	{"FELS", 15},
	{"MEER", 19},
	{"BRANDUNG", 20},
	{"BRANDECK", 21},
	{"MUENDUNG", 22},
	{"HANG", 31},
	{"HANGECK", 32},
	{"HANGQUELL", 33},
	{"STRAND", 23},
	{"STRANDVARI", 27},
	{"STRANDECKI", 26},
	{"STRANDECKA", 25},
	{"STRANDMUND", 24},
	{"STRANDHAUS", 28},
	{"PIER", 30},
	{"FLUSS", 16},
	{"FLUSSECK", 17},
	{"FISCHEREI", 6},
	{"WMUEHLE", 37},
	{"THEATER", 21},
	{"BADEHAUS", 20},
	{"KLINIK", 22},
	{"HOCHSCHULE", 24}, // 18h
	{"WIRT", 17},
	{"JAGDHAUS", 5},
	{"KIRCHE", 19},
	{"KAPELLE", 18},
	{"SCHULE", 23}, // 17h
	{"BRUNNEN", 26},
	{"SCHLOSS", 27}, // 1Bh
	{"ERZBERG_GROSS", 0},
	{"ERZBERG_KLEIN", 1},
	{"BERGWERK", 3},
	{"STEINBRUCH", 11},
	{"MAUER", 4},
	{"pMAUER", 32}, // 20h
	{"MAUERSTRAND", 5},
	{"TURM", 6},
	{"TURMSTRAND", 7},
	{"WACHTURM", 16},
	{"STRASSE", 1},
	{"PLATZ", 13},
	{"GALGEN", 25}, // 19h
	{"DENKMAL", 28}, // 1Ch
	{"TRIUMPH", 29}, // 1Dh
	{"BRUECKE", 18},
	{"HAFEN", 36},
	{"KONTOR", 8},
	{"WERFT", 14},
	{"MARKT", 7},
	{"NORUINE", 255},
	{"RUINE", 12},
	{"RUINE_FELD", 4},
	{"RUINE_HOLZ", 0},
	{"RUINE_STEIN", 2},
	{"RUINE_KONTOR_1", 8},
	{"RUINE_KONTOR_N1", 12},
	{"RUINE_KONTOR_N2", 13},
	{"RUINE_ROAD_STEIN", 6},
	{"RUINE_ROAD_FELD", 5},
	{"RUINE_MINE", 7},
	{"RUINE_MARKT", 14},
	{"STRANDRUINE", 29}, // 1Dh
	{"PIRATWOHN", 31}, // 1Fh
	{"GEBAEUDE", 14},
	{"PLANTAGE", 2},
	{"MINE", 34},
	{"HQ", 35},
	{"MILITAR", 15},
	{"RADIUS_HQ", 16}, // 10h
	{"RADIUS_MARKT", 16}, // 10h



{"GRAS", 0},
{"BAUM", 0},
{"GETREIDE", 0},
{"BAUMWOLLE", 0},
{"TABAKBAUM", 0},
{"KAKAOBAUM", 0},
{"ZUCKERROHR", 0},
{"GEWUERZBAUM", 0},
{"WEINTRAUBEN", 0},
{"MEHL", 0},
{"KORN", 0},
{"FLEISCH", 0},
{"HOLZ", 0},
{"STOFFE", 0},
{"ERZE", 0},
{"EISENERZ", 0},
{"EISEN", 0},
{"KLEIDUNG", 0},
{"WOLLE", 0},
{"ZUCKER", 0},
{"ALKOHOL", 0},
{"TABAKWAREN", 0},
{"TABAK", 0},
{"SCHMUCK", 0},
{"GOLD", 0},
{"WERKZEUG", 0},
{"MUSKETEN", 0},
{"KANONEN", 0},
{"SCHWERTER", 0},
{"STEINE", 0},
{"ZIEGEL", 0},
{"WILD", 0},
{"KAKAO", 0},
{"GEWUERZE", 0},
{"RIND", 0},
{"SCHAF", 0},
{"NAHRUNG", 0},
{"ALLWARE", 0},
{"KARREN", 0},
{"PACKESEL", 0},
{"TRAEGER", 0},
{"TRAEGER2", 0},
{"MAEHER", 0},
{"PFLUECKER", 0},
{"PFLUECKER2", 0},
{"GAUKLER1", 0},
{"SPEER1", 0},
{"FISCHE", 0},
{"FISCHER", 0},
{"FLEISCHER", 0},
{"STEINKLOPFER", 0},
{"HOLZFAELLER", 0},
{"JAEGER", 0},
{"ARZT", 0},
{"LOESCH", 0},
{"RAUCHSCHMELZ", 0},
{"RAUCHBAECK", 0},
{"RAUCHBRENNER", 0},
{"RAUCHGOLD", 0},
{"RAUCHWERKZEUG", 0},
{"RAUCHMUSKET", 0},
{"RAUCHKANONEN", 0},
{"RAUCHSCHWERT", 0},
{"TOR", 0},
{"KANONTURM", 0},
{"FAHNETURM1", 0},
{"FAHNETURM2", 0},
{"FAHNETURM3", 0},
{"FAHNEKONTOR", 0},
{"FAHNEKONTOR1", 0},
{"FAHNEKONTOR2", 0},
{"FAHNEKONTOR3", 0},
{"FAHNEKONTOR4", 0},
{"FAHNEMARKT", 0},
{"PIRATTURM", 0},
{"INFRA_KATHETRALE", 0},
{"INFRA_KIRCHE", 0},
{"INFRA_WIRT", 0},
{"INFRA_THEATER", 0},
{"INFRA_BADE", 0},
{"INFRA_ARZT", 0},
{"INFRA_HOCHSCHULE", 0},
{"INFRA_SCHULE", 0},
{"INFRA_SCHLOSS", 0},
{"INFRA_GALGEN", 0},
{"INFRA_DENKMAL", 0},
{"INFRA_TRIUMPH", 0},
{"INFRA_STUFE_1A", 0},
{"INFRA_STUFE_2A", 0},
{"INFRA_STUFE_2B", 0},
{"INFRA_STUFE_2C", 0},
{"INFRA_STUFE_2D", 0},
{"INFRA_STUFE_2E", 0},
{"INFRA_STUFE_2F", 0},
{"INFRA_STUFE_2G", 0},
{"INFRA_STUFE_3A", 0},
{"INFRA_STUFE_3B", 0},
{"INFRA_STUFE_3C", 0},
{"INFRA_STUFE_3D", 0},
{"INFRA_STUFE_3E", 0},
{"INFRA_STUFE_3F", 0},
{"INFRA_STUFE_4A", 0},
{"INFRA_STUFE_4B", 0},
{"INFRA_STUFE_5A", 0},
{"INFRA_STUFE_5B", 0},
{"WAV_STANDARD", 0},
{"WAV_KONTOR", 0},
{"WAV_NIX", 0},
{"WAV_BURG", 0},
{"WAV_MUEHLE", 0},
{"WAV_BAECKER", 0},
{"WAV_FLEISCHER", 0},
{"WAV_RUMBRENNER", 0},
{"WAV_SCHWERTBAU", 0},
{"WAV_GIESSEREI", 0},
{"WAV_MINE", 0},
{"WAV_JAGDHUETTE", 0},
{"WAV_PLANTAGE", 0},
{"WAV_WOHNHAUS", 0},
{"WAV_PYRAMIDE", 0},
{"WAV_PIRATEN", 0},
{"WAV_KATHETRALE", 0},
{"WAV_KAPELLE", 0},
{"WAV_KIRCHE", 0},
{"WAV_WIRTSHAUS", 0},
{"WAV_THEATER", 0},
{"WAV_BADEHAUS", 0},
{"WAV_MARKT", 0},
{"WAV_ARZT", 0},
{"WAV_SCHULE", 0},
{"WAV_BRUNNEN", 0},
{"WAV_SCHLOSS", 0},
{"WAV_DENKMAL", 0},
{"WAV_TRIUMPH", 0},



//	{"UNUSED", 0},
//	{"WAV_STANDARD", 0},
//	{"WAV_KONTOR", 0},
//	{"WAV_NIX", 0},
//	{"WAV_BURG", 0},
//	{"WAV_MUEHLE", 0},
//	{"WAV_BAECKER", 0},
//	{"WAV_FLEISCHER", 0},
//	{"WAV_RUMBRENNER", 0},
//	{"WAV_SCHWERTBAU", 0},
//	{"WAV_GIESSEREI", 0},
//	{"WAV_MINE", 0},
//	{"WAV_JAGDHUETTE", 0},
//	{"WAV_PLANTAGE", 0},
//	{"WAV_WOHNHAUS", 0},
//	{"WAV_PYRAMIDE", 0},
//	{"WAV_PIRATEN", 0},
//	{"WAV_KATHETRALE", 0},
//	{"WAV_KAPELLE", 0},
//	{"WAV_KIRCHE", 0},
//	{"WAV_WIRTSHAUS", 0},
//	{"WAV_THEATER", 0},
//	{"WAV_BADEHAUS", 0},
//	{"WAV_MARKT", 0},
//	{"WAV_ARZT", 0},
//	{"WAV_SCHULE", 0},
//	{"WAV_BRUNNEN", 0},
//	{"WAV_SCHLOSS", 0},
//	{"WAV_DENKMAL", 0},
//	{"WAV_TRIUMPH", 0},
//	{"TIMENEVER", 0},
//	{"NOWARE", 0},
//	{"MAXPRODCNT", 0},
//	{"MAXHAUS", 0},
//	{"BODEN", 0},
//	{"ROHSTWACHS", 0},
//	{"ROHSTOFF", 0},
//	{"GRAS", 0},
//	{"WALD", 0},
//	{"BAUM", 0},
//	{"GETREIDE", 0},
//	{"BAUMWOLLE", 0},
//	{"TABAKBAUM", 0},
//	{"KAKAOBAUM", 0},
//	{"ZUCKERROHR", 0},
//	{"GEWUERZBAUM", 0},
//	{"WEINTRAUBEN", 0},
//	{"MEHL", 0},
//	{"KORN", 0},
//	{"FLEISCH", 0},
//	{"HOLZ", 0},
//	{"STOFFE", 0},
//	{"ROHSTERZ", 0},
//	{"ERZE", 0},
//	{"EISENERZ", 0},
//	{"EISEN", 0},
//	{"KLEIDUNG", 0},
//	{"WOLLE", 0},
//	{"ZUCKER", 0},
//	{"ALKOHOL", 0},
//	{"TABAKWAREN", 0},
//	{"TABAK", 0},
//	{"SCHMUCK", 0},
//	{"GOLD", 0},
//	{"WERKZEUG", 0},
//	{"MUSKETEN", 0},
//	{"KANONEN", 0},
//	{"SCHWERTER", 0},
//	{"STEINE", 0},
//	{"ZIEGEL", 0},
//	{"WILD", 0},
//	{"KAKAO", 0},
//	{"GEWUERZE", 0},
//	{"RIND", 0},
//	{"SCHAF", 0},
//	{"NAHRUNG", 0},
//	{"ALLWARE", 0},
//	{"KARREN", 0},
//	{"PACKESEL", 0},
//	{"TRAEGER", 0},
//	{"TRAEGER2", 0},
//	{"MAEHER", 0},
//	{"PFLUECKER", 0},
//	{"PFLUECKER2", 0},
//	{"WEIDETIER", 0},
//	{"GAUKLER1", 0},
//	{"SPEER1", 0},
//	{"HANDWERK", 0},
//	{"HANG", 0},
//	{"FELS", 0},
//	{"MEER", 0},
//	{"FISCHE", 0},
//	{"FISCHER", 0},
//	{"BRANDUNG", 0},
//	{"BRANDECK", 0},
//	{"MUENDUNG", 0},
//	{"HANGQUELL", 0},
//	{"HANGECK", 0},
//	{"STRAND", 0},
//	{"STRANDVARI", 0},
//	{"STRANDECKI", 0},
//	{"STRANDECKA", 0},
//	{"STRANDMUND", 0},
//	{"STRANDHAUS", 0},
//	{"PIER", 0},
//	{"FLUSS", 0},
//	{"FLUSSECK", 0},
//	{"FISCHEREI", 0},
//	{"FLEISCHER", 0},
//	{"WMUEHLE", 0},
//	{"STEINKLOPFER", 0},
//	{"HOLZFAELLER", 0},
//	{"THEATER", 0},
//	{"BADEHAUS", 0},
//	{"KLINIK", 0},
//	{"HOCHSCHULE", 0},
//	{"WIRT", 0},
//	{"JAEGER", 0},
//	{"JAGDHAUS", 0},
//	{"KIRCHE", 0},
//	{"KAPELLE", 0},
//	{"ARZT", 0},
//	{"SCHULE", 0},
//	{"BRUNNEN", 0},
//	{"LOESCH", 0},
//	{"SCHLOSS", 0},
//	{"RAUCHSCHMELZ", 0},
//	{"RAUCHBAECK", 0},
//	{"RAUCHBRENNER", 0},
//	{"RAUCHGOLD", 0},
//	{"RAUCHWERKZEUG", 0},
//	{"RAUCHMUSKET", 0},
//	{"RAUCHKANONEN", 0},
//	{"RAUCHSCHWERT", 0},
//	{"ERZBERG_GROSS", 0},
//	{"ERZBERG_KLEIN", 0},
//	{"BERGWERK", 0},
//	{"STEINBRUCH", 0},
//	{"MAUER", 0},
//	{"pMAUER", 0},
//	{"MAUERSTRAND", 0},
//	{"TOR", 0},
//	{"TURM", 0},
//	{"TURMSTRAND", 0},
//	{"WACHTURM", 0},
//	{"KANONTURM", 0},
//	{"FAHNETURM1", 0},
//	{"FAHNETURM2", 0},
//	{"FAHNETURM3", 0},
//	{"STRASSE", 0},
//	{"PLATZ", 0},
//	{"GALGEN", 0},
//	{"DENKMAL", 0},
//	{"TRIUMPH", 0},
//	{"BRUECKE", 0},
//	{"WOHNUNG", 0},
//	{"HAFEN", 0},
//	{"WERFT", 0},
//	{"KONTOR", 0},
//	{"FAHNEKONTOR", 0},
//	{"FAHNEKONTOR1", 0},
//	{"FAHNEKONTOR2", 0},
//	{"FAHNEKONTOR3", 0},
//	{"FAHNEKONTOR4", 0},
//	{"MARKT", 0},
//	{"FAHNEMARKT", 0},
//	{"NORUINE", 0},
//	{"RUINE", 0},
//	{"RUINE_FELD", 0},
//	{"RUINE_HOLZ", 0},
//	{"RUINE_STEIN", 0},
//	{"RUINE_KONTOR_1", 0},
//	{"RUINE_KONTOR_N1", 0},
//	{"RUINE_KONTOR_N2", 0},
//	{"RUINE_ROAD_STEIN", 0},
//	{"RUINE_ROAD_FELD", 0},
//	{"RUINE_MINE", 0},
//	{"RUINE_MARKT", 0},
//	{"STRANDRUINE", 0},
//	{"PIRATWOHN", 0},
//	{"PIRATTURM", 0},
//	{"GEBAEUDE", 0},
//	{"PLANTAGE", 0},
//	{"MINE", 0},
//	{"HQ", 0},
//	{"MILITAR", 0},
//	{"INFRA_KATHETRALE", 0},
//	{"INFRA_KIRCHE", 0},
//	{"INFRA_WIRT", 0},
//	{"INFRA_THEATER", 0},
//	{"INFRA_BADE", 0},
//	{"INFRA_ARZT", 0},
//	{"INFRA_HOCHSCHULE", 0},
//	{"INFRA_SCHULE", 0},
//	{"INFRA_SCHLOSS", 0},
//	{"INFRA_GALGEN", 0},
//	{"INFRA_DENKMAL", 0},
//	{"INFRA_TRIUMPH", 0},
//	{"INFRA_STUFE_1A", 0},
//	{"INFRA_STUFE_2A", 0},
//	{"INFRA_STUFE_2B", 0},
//	{"INFRA_STUFE_2C", 0},
//	{"INFRA_STUFE_2D", 0},
//	{"INFRA_STUFE_2E", 0},
//	{"INFRA_STUFE_2F", 0},
//	{"INFRA_STUFE_2G", 0},
//	{"INFRA_STUFE_3A", 0},
//	{"INFRA_STUFE_3B", 0},
//	{"INFRA_STUFE_3C", 0},
//	{"INFRA_STUFE_3E", 0},
//	{"INFRA_STUFE_3F", 0},
//	{"INFRA_STUFE_4A", 0},
//	{"INFRA_STUFE_4B", 0},
//	{"INFRA_STUFE_5A", 0},
//	{"INFRA_STUFE_5B", 0},
//	{"RADIUS_HQ", 0},
//	{"RADIUS_MARKT", 0},
};
